Sistema de recomendaci√≥n basado en el contenido

In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.neighbors import NearestNeighbors

In [30]:
imdb = pd.read_csv('imdb_top_1000.csv')
imdb.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [31]:
imdb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   object
 1   Series_Title   1000 non-null   object
 2   Released_Year  1000 non-null   object
 3   Certificate    899 non-null    object
 4   Runtime        1000 non-null   object
 5   Genre          1000 non-null   object
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object
 10  Star1          1000 non-null   object
 11  Star2          1000 non-null   object
 12  Star3          1000 non-null   object
 13  Star4          1000 non-null   object
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    object
dtypes: float64(2), int64(1), object(13)
memory usage: 125.1+ KB

In [32]:
# Trabajaremos unicamente con las columnas Series_title, Genre, IMDB_Rating, Director, Star1, Star2
columnas = ['Series_Title','Genre','IMDB_Rating','Director','Star1','Star2']
imdb_recomendacion = imdb[columnas]
imdb_recomendacion.head()

,Series_Title,Genre,IMDB_Rating,Director,Star1,Star2
0,The Shawshank Redemption,Drama,9.3,Frank Darabont,Tim Robbins,Morgan Freeman
1,The Godfather,"Crime, Drama",9.2,Francis Ford Coppola,Marlon Brando,Al Pacino
2,The Dark Knight,"Action, Crime, Drama",9.0,Christopher Nolan,Christian Bale,Heath Ledger
3,The Godfather: Part II,"Crime, Drama",9.0,Francis Ford Coppola,Al Pacino,Robert De Niro
4,12 Angry Men,"Crime, Drama",9.0,Sidney Lumet,Henry Fonda,Lee J. Cobb

In [33]:
#Aplicamos che a las variables categ√≥ricas
imdb_recomendacion_t = pd.get_dummies(
    imdb_recomendacion,
    columns = ['Genre', 'Director', 'Star1', 'Star2']
    )
imdb_recomendacion_t

,Series_Title,IMDB_Rating,"Genre_Action, Adventure","Genre_Action, Adventure, Biography","Genre_Action, Adventure, Comedy","Genre_Action, Adventure, Crime","Genre_Action, Adventure, Drama","Genre_Action, Adventure, Family","Genre_Action, Adventure, Fantasy","Genre_Action, Adventure, History",...,Star2_Yul Brynner,Star2_Yuriko Ishida,Star2_Yutaka Sada,Star2_Zach Galifianakis,Star2_Zachary Quinto,Star2_Zack Gottsagen,Star2_Zbigniew Zamachowski,Star2_Zoe Saldana,Star2_√áetin Tekindor,Star2_√ñzge √ñzberk
0,The Shawshank Redemption,9.3,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,The Godfather,9.2,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,The Dark Knight,9.0,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,The Godfather: Part II,9.0,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,12 Angry Men,9.0,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,7.6,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
996,Giant,7.6,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
997,From Here to Eternity,7.6,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
998,Lifeboat,7.6,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
999,The 39 Steps,7.6,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [34]:
imdb_recomendacion_t.shape

(1000, 2253)

In [35]:
#Creamos el modelo
knn = NearestNeighbors(n_neighbors= 10)
knn

NearestNeighbors(n_neighbors=10)

In [36]:
#Ajustamos el modelo de recomendaci√≥n
recomendacion = knn.fit(imdb_recomendacion_t.drop(columns = ['Series_Title']))

In [37]:
#Hacemos las predicciones
distancias, indices = recomendacion.kneighbors(imdb_recomendacion_t.drop(columns=['Series_Title']))

In [38]:
indices[1]
distancias[1]

array([0.        , 2.00997512, 2.45764115, 2.46779254, 2.52190404,
       2.56124969, 2.57681975, 2.57681975, 2.60959767, 2.60959767])

In [39]:
indice = imdb_recomendacion_t[imdb_recomendacion_t['Series_Title'] == 'The Dark Knight'].index[0]
Pelicula = imdb_recomendacion_t.loc[indices[indice], 'Series_Title']
Calificacion = imdb_recomendacion_t.loc[indices[indice], 'IMDB_Rating']
Calificacion

2      9.0
36     8.5
63     8.4
155    8.2
8      8.8
21     8.6
42     8.5
55     8.4
69     8.4
201    8.1
Name: IMDB_Rating, dtype: float64

In [40]:
#Creamos una funci√≥n para hacer las recomendaciones
def recomendacion_pelicula(pelicula):
    #Buscamos el indice de la pelicula
    indice = imdb_recomendacion_t[imdb_recomendacion_t['Series_Title'] == pelicula].index[0]
    #Creamos un dataframe con las peliculas mas cercanas
    resultado = pd.DataFrame(
        {
            'Pelicula' : imdb_recomendacion.loc[indices[indice],'Series_Title'],
            'Calificacion' : imdb_recomendacion.loc[indices[indice], 'IMDB_Rating']
         }   
        )
    return resultado

recomendacion_pelicula('The Dark Knight')

                  Pelicula  Calificacion
2          The Dark Knight           9.0
36            The Prestige           8.5
63   The Dark Knight Rises           8.4
155          Batman Begins           8.2
8                Inception           8.8
21            Interstellar           8.6
42                    L√©on           8.5
55            Vikram Vedha           8.4
69                 Memento           8.4
201                 Haider           8.1